version: '2'
services:
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    env_file:
      - .env
    expose:
      - 5672
      - 15672
    depends_on:
      - database
    restart: always

  database:
    image: postgres
    hostname: database
    env_file:
      - .env
    expose:
     - 5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    hostname: web
    build:
      context: ..
      dockerfile: server/Dockerfile
    volumes:
      - ./logs:/var/log/rematch
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - RABBITMQ_HOST=rabbitmq
      - DJANGO_SETTINGS_MODULE=rematch.settings.docker
      - DJANGO_LOG_FILE=/var/log/rematch/django.log
    links:
      - "database:database"
      - "rabbitmq:rabbitmq"
    depends_on:
      - database
      - rabbitmq
    restart: always
